# This workflow checks out code and scans the content changed or added in the 
# last commit for offensive / exclusive terms.
# The scan will provide context on the found terms and alternatvies that can be
# used instead.

name: Inclusiveness Analyser scan

on:
  push:
  workflow_dispatch:

jobs:
  Inclusiveness-Analyser-scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Inclusiveness Analyzer
      uses: microsoft/InclusivenessAnalyzer@v1.0.1
      with:
        failOnNonInclusiveTerm: true
        excludeUnchangedFiles: false
        excludeFiles: >-
          .tox,
          .github,
          # .README.html,
          **/.sanity-ansible-ignore-*.txt,
          CHANGELOG.md,
          pylintrc,
          vendor,
          tests/sanity,
          **/templates/*master*
        excludeTerms:
